services:
  blinkbridge:
    image: rogerdammit/blinkbridge
    volumes:
      - /Volumes/Space/blinkbridge-1/config.json:/app/config.json
      # path for temporary files (video clips, concat files, etc.)
      - /tmp/blinkbridge:/working
      # use below instead to use RAM instead of disk for temporary files
      # - type: tmpfs
      #   target: /working
      #   tmpfs:
      #     size: 52428800  # 50MB  
    tty: true # for color logs
    environment:
      - BLINKBRIDGE_CONFIG=/app/config.json
  mediamtx:
    image: bluenviron/mediamtx
    container_name: mediamtx
    ports:
      - 8555:8554